name: CI Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Build docs
        run: npm run demo:build
